name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-18.04
    #env:
    #  AWS_ACCESS_KEY_ID: ASIA3H4P5VZX7UR645E4
    #  AWS_SECRET_ACCESS_KEY: OQlrX4WcQyjBdwird4Kzz7JUQZoigLyDHhYAyv8b
    #  AWS_DEFAULT_REGION: us-east-1

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile_mysql --tag mysql
    #- uses: actions/checkout@v3
    #- name: AWS credentials
    #  run: mkdir ~/.aws && touch ~/.aws/credentials && echo "[default]" >> ~/.aws/credentials && echo "aws_access_key_id=ASIA3H4P5VZX7UR645E4" >> ~/.aws/credentials && echo "aws_secret_access_key=OQlrX4WcQyjBdwird4Kzz7JUQZoigLyDHhYAyv8b" >> ~/.aws/credentials && echo "aws_session_token=FwoGZXIvYXdzEKv//////////wEaDNb2rUjGuc2wBVPseSLAATzBX2kfrTtaGyBIO1Up53sGuB40Syju8hq443jnl/rskRM2vOpONiDSZS4rYAm5Qgi1HMrIYbbR3zkYxq8ANhv01Fa4tPAEsP0RJCDKAKnM3W1e5FjApXKNKG82Xi51G5HbhgbP1VzIg9EsYsWiuBbAO5QxQuyLqcPUlBLcPewuiYrA7kxIxgCvggEC4MGxVJMS75rFPsS71IWt+kej6RdjJpG9lCX5XymCsSoRAMny7bvTAoM81gYLb68yJOw20yjwi9mZBjItMNA7Ry6pLzHVoTejhp6JsMNS7YPfKpfCKyeRk9Nfob5Xa81ctJkEymkUwXuH" >> ~/.aws/credentials && cat ~/.aws/credentials
    - uses: actions/checkout@v3
    - name: AWS configure
      run: aws configure set aws_access_key_id ASIA3H4P5VZXTAG5254I && aws configure set aws_secret_access_key aHVx9f3rYuEYDNjFpsbXnyY2AcOv26zz5E3KEkWp && aws configure set aws_session_token FwoGZXIvYXdzEK///////////wEaDCLHSkgN85p5Fup87iLAAePmY6RvQfUA0RU9yjMxroO930p0WuCvEk/4rSuLjwNrlf3Cbt8eYqAnCTyOuGHQes5XAzrc4lHVVOxPvhjuS92K0Acd/mPi2IhpktjepewwP/vYuUg7ZxY+fGji1yAPrTieorX5Nh0E+kFvKdF8ntOkjVKf3YwKaCVzUagPfBrKNt6JcxZIjS1eSyD+dGrbT6DIVWgw57M2q7If6VOirdqiViH5VO5hnYRf6qGdLB0fph5OH5r+DURqUHZWKyDi5SiDhdqZBjItqBExsAZSs36lPUBZl0OVj3MC1Mk1NqOiYaiVU9nFcXnmxai151vMSEXxyEBH && export AWS_DEFAULT_REGION=us-east-1
    - uses: actions/checkout@v3
    - name: Login to AWS
      #run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 772859080303.dkr.ecr.us-east-1.amazonaws.com/clo835assignment1
      run: docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 772859080303.dkr.ecr.us-east-1.amazonaws.com
    - name: Pushing a docker image_app
      run: docker push clo835assignment1/app
    - name: Pushing a docker image
      run: docker push clo835assignment1/mysql
