name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile_mysql --tag mysql
    - uses: actions/checkout@v3
    - name: Login to AWS
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 772859080303.dkr.ecr.us-east-1.amazonaws.com/clo835assignment1
    - uses: actions/checkout@v3
    - name: Pushing a docker image
      run: docker push 772859080303.dkr.ecr.us-east-1.amazonaws.com/clo835assignment1
